function swe_ui_main2

    %-Open SwE menu window
    %----------------------------------------------------------------------
    S = get(0,'ScreenSize');
    F = figure('Color',[0 0.95 1]*.8,...
        'Name','SwE Toolbox',...
        'NumberTitle','off',...
        'Position',[S(3)/2-200,S(4)/2-140,300,300],...
        'Resize','off',...
        'Tag','SnPM Menu',...
        'Pointer','Watch',...
        'MenuBar','none',...
        'Visible','off');

    %-Outer Frames and text
    %----------------------------------------------------------------------
    axes('Position',[0 0 80/300 300/300],'Visible','Off')
    text(0.5,0.475,'SwE',...
        'FontName','Times','FontSize',72,...
        'Rotation',90,...
        'VerticalAlignment','middle','HorizontalAlignment','center',...
        'Color',[1 1 1]*.5);
    
    text(0.2,0.96,'Sandwich Estimator Toolbox',...
        'FontName','Times','FontSize',16,'FontAngle','Italic',...
        'FontWeight','Bold',...
        'Color',[1 1 1]*.5);
    
    %-Inner Frames
    %----------------------------------------------------------------------
    uicontrol(F,'Style','Frame','Position',[095 005 200 270],...
              'BackgroundColor',[0.8 0.8 1.0]*.7);
    uicontrol(F,'Style','Frame','Position',[105 015 180 250]);
    
    %-Buttons to launch SnPM functions
    %-----------------------------------------------------------------------
    uicontrol(F,'Style','Text',...
        'String','Analysis',...
        'HorizontalAlignment','Center',...
        'Position',[115 230 160 030],...
        'ForegroundColor','w');

    uicontrol(F,'String','Specify Model',...
        'Position',[115 220-(1-1)*35 130 025],...
        'CallBack','',...
        'Interruptible','on',...
        'ForegroundColor','k');
    
    uicontrol(F,'String','Run Model',...
        'Position',[115 220-(2-1)*35 130 025],...
        'CallBack','snpm_cp',...
        'Interruptible','on',...
        'ForegroundColor','k');
    uicontrol(F,'String','?',...
        'Position',[250 220-(2-1)*35 025 025],...
        'CallBack','spm_help(''snpm_cp.m'')',...
        'Interruptible','on',...
        'ForegroundColor','g');
    
    uicontrol(F,'String','Results',...
        'Position',[115 220-(3-1)*35 130 025],...
        'CallBack','snpm_cp',...
        'Interruptible','on',...
        'ForegroundColor','k');
    uicontrol(F,'String','?',...
        'Position',[250 220-(3-1)*35 025 025],...
        'CallBack','spm_help(''snpm_cp.m'')',...
        'Interruptible','on',...
        'ForegroundColor','g');
    
    
    %-Make visible
    %----------------------------------------------------------------------
    set(F,'Pointer','Arrow','Visible','on')

    
    
end