function swe_ui_main2

    %-Open SwE menu window
    %----------------------------------------------------------------------
    S = get(0,'ScreenSize');
    F = figure('Color',[0 0.9 1]*.85,...
        'Name','SwE Toolbox',...
        'NumberTitle','off',...
        'Position',[S(3)/2-200,S(4)/2-140,300,320],...
        'Resize','off',...
        'Tag','SnPM Menu',...
        'Pointer','Watch',...
        'MenuBar','none',...
        'Visible','off');

    %-Frames and text
    %----------------------------------------------------------------------
    axes('Position',[0 0 80/300 320/320],'Visible','Off')
    text(0.5,0.475,'SwE',...
        'FontName','Times','FontSize',72,...
        'Rotation',90,...
        'VerticalAlignment','middle','HorizontalAlignment','center',...
        'Color',[1 1 1]*.6);
    
    
    %-Make visible
    %----------------------------------------------------------------------
    set(F,'Pointer','Arrow','Visible','on')

    
    
end